# Generated by Django 4.2.7 on 2023-12-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('roll', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
    ]
